### ISSUE TITLE
Feedback from @vincenzospaghetti on Questionnaire v0.9.1

### ISSUE THREAD

**Issue by linxule** [Ledgerback/DGSF#28]
**Assigned To:**

@vincenzospaghetti 

**Objective:**

Review and comment on DAO Index_Draft v0.9.1

**Information to Review:**

feel free to edit or make a copy of [DAO Index_Draft_XL: v0.9.1](https://airtable.com/appxwnyzem8EAbGtk/tblHVUkQTReLlfZm2/viwNIMm7TFEQqelHu?blocks=hide)

**Links:**

[DAO Index_Draft_XL: v0.9.1](https://airtable.com/appxwnyzem8EAbGtk/tblHVUkQTReLlfZm2/viwNIMm7TFEQqelHu?blocks=hide)

**Questions from Task Creator (if any):**

@kylefox1  would you like this to be on NocoDB instead?

**Comment by kylefox1** [comment]
> **Questions from Task Creator (if any):**
> 
> @kylefox1 would you like this to be on NocoDB instead?

Yes.

**Comment by linxule** [comment]
Can you link and specify which sheet/table you want us to leave our feedback?

**Comment by linxule** [comment]
> 
> 
> 
> 
> > **Questions from Task Creator (if any):**
> 
> > 
> 
> > @kylefox1 would you like this to be on NocoDB instead?
> 
> 
> 
> Yes. 
> 
> 

Can you link and specify which sheet/table you want us to leave our feedback?

**Comment by kylefox1** [comment]
> > > **Questions from Task Creator (if any):**
> > 
> > 
> > > 
> > 
> > 
> > > @kylefox1 would you like this to be on NocoDB instead?
> > 
> > 
> > Yes.
> 
> Can you link and specify which sheet/table you want us to leave our feedback?

Questionnaire-V09
